<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="/assets/css/style.css">
    </head>
    <body class="home-page">
        <div class="welcome-text">
            <h1 class="page-header">Slim</h1>
            <?php if (isset($name)) : ?>
                <h2 class="page-subheader">Hello <?= htmlspecialchars($name); ?>!</h2>
            <?php endif; ?>
            <p><a href="http://www.slimframework.com">www.slimframework.com</a></p>
        </div>
        <footer>
            <script src="/assets/js/script.js"></script>
        </footer>
    </body>
</html>
